owners:
  - Martin Jackson
triggers:
  branches:
  - name: main
    versions:
    - '4.12'
    - '4.11'
  - name: 'v1.1'
    versions:
    - '4.10'

  openshift:
  - version: '4.12'
    branch: main
    platform: gcp
  - version: '4.11'
    branch: main
    platform: azure
  - version: '4.10'
    branch: 'v1.1'
    platform: aws

  subscriptions:
  - openshift-gitops: main
