triggers:
  branches:
  - main:
    - 4.12
    - 4.11
  - 'v2.2':
    - 4.10
    - 4.9
    - 4.8

  openshift:
  - 4.12: aws 
  - 4.11: gcp
  - 4.10: azure
  - 4.9:  aws
  - 4.8:  gcp

  subscriptions:
  - openshift-gitops: main
