triggers:
  upstream:
  - main:
    - ocp: '4.11'
      platform: azure
    - ocp: '4.10'
      platform: gcp
  
  openshift:
  - ocp: '4.12'
    platform: gcp
  - ocp: '4.11'
    platform: aws
  - ocp: '4.10'
    platform: azure
     
  subscriptions:
  - ocp: '4.11'
    branch: main
    platform: gcp
