owners:
  - jrickard
triggers:
  branches:
  - name: main
    versions:
    - '4.12'
  - name: 'stable-4.11-v2.3'
    versions:
    - '4.10'
    - '4.11'

  openshift:
  - version: '4.12'
    branch: main
    platform: azure
  - version: '4.11'
    branch: 'stable-4.11-v2.3'
    platform: aws
  - version: '4.10'
    branch: 'stable-4.11-v2.3'
    platform: gcp

  subscriptions:
  - openshift-gitops: main

