triggers:
  branches:
  - main:
    - 4.12
  - 'stable-4.11-v1.0':
    - 4.11
  - 'stable-4.10-v2.3':
    - 4.10

  openshift:
  - 4.12: azure 
  - 4.11: aws
  - 4.10: gcp

  subscriptions:
  - openshift-gitops: main
  
