triggers:
  branches:
  - main:
    - 4.12
    - 4.11
    - 4.10
  - 'v1.1':
    - 4.9
    - 4.8

  openshift:
  - 4.12: gcp 
  - 4.11: azure
  - 4.10: aws
  - 4.9:  gcp
  - 4.8:  azure

  subscriptions:
  - openshift-gitops: main
