triggers:
  upstream:
  - main:
    - ocp: '4.11'
      platform: aws
    - ocp: '4.10'
      platform: gcp
    - ocp: '4.9'
      platform: azure
  - 'v1.0':
    - ocp: '4.8'
      platform: aws
  
  openshift:
  - ocp: '4.8'
    platform: gcp
  - ocp: '4.9'
    platform: aws
  - ocp: '4.10'
    platform: azure
  - ocp: '4.11'
    platform: gcp
  - ocp: '4.12'
    platform: azure
     
  subscriptions:
  - ocp: '4.11'
    branch: main
    platform: aws
